version: "3.8"

services:
  app:
#    image: get_user_info
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_IP=PostgresCont
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USER=postgres
      - DB_PASS=indocyber
      - URL_HOST=jdbc:postgresql://localhost:5432/postgres
    depends_on:
      - PostgresCont

  PostgresCont:
    image: postgres:latest
    network_mode: host
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./initsql:/docker-entrypoint-initdb.d